[General]
; The general text scale for the... text. (Default: 2.0)
TextScale=2.0
; The padding of the text from the top right of the screen. (Default: 24.0)
Padding=24.0
; Whether the text should disappear after a few seconds. (Default: False)
Disappear=0
; Whether the text should animate before changing text. (Default: True)
ChangeAnimation=1
; Which monitor should this reside in?
Monitor=1
