.TH deltatunix 7 "6 May 2026" "version 0.1.0"
.SH NAME
deltatunix - A music indicator for linux desktops, inspired by DeltaTune
.SH DESCRIPTION
.B deltatunix
is a music indicator for linux desktops, and mostly iterates
on Toastworth's DeltaTune, except this is for Linux and has
more customization features.

.PP
Note that this project is still a 
.B "work " "in " "progress "
and therefore may have issues.
